# 在这里声明当前是开发环境或生产环境（dev or produce）
spring:
  profiles:
    active: dev
  datasource:
    druid:
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: false
      # 登陆名和密码
      stat-view-servlet:
        login-username: blysin
        login-password: blysin
  freemarker:
      template-loader-path: classpath:/views/
      expose-request-attributes: true
      expose-session-attributes: true
      request-context-attribute: request
      suffix: .ftl
      prefer-file-system-access: false
      cache: false
  mvc:
    static-path-pattern: /static/**
  devtools:
    restart:
      exclude: static/**




mybatis:
  mapper-locations: classpath:mappers/*/*.xml
  configuration:
      log-impl: org.apache.ibatis.logging.log4j.Log4jImpl
      map-underscore-to-camel-case: true
  type-aliases-package: cn.blysin.leshop.*.domain
server:
  port: 8071


---
# 开发环境下的配置

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/le38?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root

blysin:
  debugger: false
  name: 现在是开发环境



---
# 生产环境下的配置

spring:
  profiles: produce
  datasource:
    url: jdbc:mysql://localhost:3306/guns?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

blysin:
  debugger: true
  name: 现在是生产环境
